---
name: Sunsynk/Deye Inverter Add-on (my modbus)
version: "0.8.2"
image: ghcr.io/kellerza/hass-addon-sunsynk-multi
slug: hass-addon-sunsynk-modbus
description: Add-on for a Sunsynk/Deye branded Inverter + general modbus
startup: services
boot: auto
url: "https://github.com/urbanbur/ha-addons/tree/main/modbus_ctrl"
uart: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports: {}
ports_description: {}
host_network: false
map:
  - share:rw
options:
  DRIVER: "pymodbus"
  INVERTERS:
    - SERIAL_NR:  !!binary | AAAAAAAAAAoAAG
      HA_PREFIX: MBus
      MODBUS_ID: 20
      DONGLE_SERIAL_NUMBER: "0"
      PORT: "tcp://homeassistant.local:502"
  SENSOR_DEFINITIONS: single-phase
  SENSORS:
  SENSORS_FIRST_INVERTER:
    - mysensors
  MANUFACTURER: MySensors
  READ_ALLOW_GAP: 2
  READ_SENSORS_BATCH_SIZE: 20
  SCHEDULES:
    - KEY: W
      READ_EVERY: 5
      REPORT_EVERY: 60
      CHANGE_ANY: false
      CHANGE_BY: 80
      CHANGE_PERCENT: 0
  NUMBER_ENTITY_MODE: "auto"
  PROG_TIME_INTERVAL: 15
  MQTT_HOST: core-mosquitto
  MQTT_PORT: 1883
  MQTT_USERNAME: hass
  MQTT_PASSWORD: ""
schema:
  DRIVER: list(pymodbus)
  INVERTERS:
    - SERIAL_NR: str
      HA_PREFIX: str
      MODBUS_ID: int(1,254)
      DONGLE_SERIAL_NUMBER: str?
      PORT: str
  SENSOR_DEFINITIONS: list(single-phase|three-phase|three-phase-hv)
  SENSORS:
    - str
  SENSORS_FIRST_INVERTER:
    - str
  MANUFACTURER: str
  READ_ALLOW_GAP: int(1,50)
  READ_SENSORS_BATCH_SIZE: int(1,100)
  SCHEDULES:
    - KEY: str
      READ_EVERY: int(1,3600)
      REPORT_EVERY: int(2,3600)
      CHANGE_ANY: bool?
      CHANGE_BY: int(0,3600)?
      CHANGE_PERCENT: int(0,500)?
  NUMBER_ENTITY_MODE: list(auto|box|slider)
  PROG_TIME_INTERVAL: list(5|10|15|30|45|60)?
  MQTT_HOST: str
  MQTT_PORT: port
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  DEBUG: int(0,5)?
  DEBUG_DEVICE: device(subsystem=tty)?
