build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
labels:
  org.opencontainers.image.title: "Firefox Home Assistant Add-on"
  org.opencontainers.image.description: "Docker container for Firefox"
  org.opencontainers.image.source: "https://github.com/urbanbur/Hikvision-SDK"
  org.opencontainers.image.licenses: "MIT"
